class CreateStylesheets < ActiveRecord::Migration
  def change
    create_table :stylesheets do |t|
      t.string :gray_base, null: false, default: '#000'
      t.string :gray_darker, null: false, default: 'lighten($gray-base, 13.5%)'
      t.string :gray_dark, null: false, default: 'lighten($gray-base, 20%)'
      t.string :gray, null: false, default: 'lighten($gray_base, 33.5%)'
      t.string :gray_light, null: false, default: 'lighten($gray-base, 46.7%)'
      t.string :gray_lighter, null: false, default: 'lighten($gray-base, 93.5%)'
      t.string :brand_primary, null: false, default: 'darken(#428bca, 6.5%)'
      t.string :brand_success, null: false, default: '#5cb85c'
      t.string :brand_info, null: false, default: '#5bc0de'
      t.string :brand_warning, null: false, default: '#f0ad4e'
      t.string :brand_danger, null: false, default: '#d9534f'
      t.string :body_bg, null: false, default: '#fff'
      t.string :text_color, null: false, default: '$gray-dark'
      t.string :link_color, null: false, default: '$brand-primary'
      t.string :link_hover_color, null: false, default: 'darken($link-color, 15%)'
      t.string :link_hover_decoration, null: false, default: 'underline'
      t.string :font_family_sans_serif, null: false, default: '"Helvetica Neue", Helvetica, Arial, sans-serif'
      t.string :font_family_serif, null: false, default: 'Georgia, "Times New Roman", Times, serif'
      t.string :font_family_monospace, null: false, default: 'Menlo, Monaco, Consolas, "Courier New", monospace'
      t.string :font_family_base, null: false, default: '$font-family-sans-serif'
      t.string :font_size_base, null: false, default: '14px'
      t.string :font_size_large, null: false, default: 'ceil(($font-size-base * 1.25))'
      t.string :font_size_small, null: false, default: 'ceil(($font-size-base * 0.85))'
      t.string :font_size_h1, null: false, default: 'floor(($font-size-base * 2.6))'
      t.string :font_size_h2, null: false, default: 'floor(($font-size-base * 2.15))'
      t.string :font_size_h3, null: false, default: 'ceil(($font-size-base * 1.7))'
      t.string :font_size_h4, null: false, default: 'ceil(($font-size-base * 1.25))'
      t.string :font_size_h5, null: false, default: '$font-size-base'
      t.string :font_size_h6, null: false, default: 'ceil(($font-size-base * 0.85))'
      t.string :line_height_base, null: false, default: '1.428571429'
      t.string :line_height_computed, null: false, default: 'floor(($font-size-base * $line-height-base))'
      t.string :headings_font_family, null: false, default: 'inherit'
      t.string :headings_font_weight, null: false, default: '500'
      t.string :headings_line_height, null: false, default: '1.1'
      t.string :headings_color, null: false, default: 'inherit'
      t.string :icon_font_path, null: false, default: 'if($bootstrap-sass-asset-helper, "bootstrap/", "../fonts/bootstrap/")'
      t.string :icon_font_name, null: false, default: '"glyphicons-halflings-regular"'
      t.string :icon_font_svg_id, null: false, default: '"glyphicons_halflingsregular"'
      t.string :padding_base_vertical, null: false, default: '6px'
      t.string :padding_base_horizontal, null: false, default: '12px'
      t.string :padding_large_vertical, null: false, default: '10px'
      t.string :padding_large_horizontal, null: false, default: '16px'
      t.string :padding_small_vertical, null: false, default: '5px'
      t.string :padding_small_horizontal, null: false, default: '10px'
      t.string :padding_xs_vertical, null: false, default: '1px'
      t.string :padding_xs_horizontal, null: false, default: '5px'
      t.string :line_height_large, null: false, default: '1.3333333'
      t.string :line_height_small, null: false, default: '1.5'
      t.string :border_radius_base, null: false, default: '4px'
      t.string :border_radius_large, null: false, default: '6px'
      t.string :border_radius_small, null: false, default: '3px'
      t.string :component_active_color, null: false, default: '#fff'
      t.string :component_active_bg, null: false, default: '$brand-primary'
      t.string :caret_width_base, null: false, default: '4px'
      t.string :caret_width_large, null: false, default: '5px'
      t.string :table_cell_padding, null: false, default: '8px'
      t.string :table_condensed_cell_padding, null: false, default: '5px'
      t.string :table_bg, null: false, default: 'transparent'
      t.string :table_bg_accent, null: false, default: '#f9f9f9'
      t.string :table_bg_hover, null: false, default: '#f5f5f5'
      t.string :table_bg_active, null: false, default: '$table-bg-hover'
      t.string :table_border_color, null: false, default: '#ddd'
      t.string :btn_font_weight, null: false, default: 'normal'
      t.string :btn_default_color, null: false, default: '#333'
      t.string :btn_default_bg, null: false, default: '#fff'
      t.string :btn_default_border, null: false, default: '#ccc'
      t.string :btn_primary_color, null: false, default: '#fff'
      t.string :btn_primary_bg, null: false, default: '$brand-primary'
      t.string :btn_primary_border, null: false, default: 'darken($btn-primary-bg, 5%)'
      t.string :btn_success_color, null: false, default: '#fff'
      t.string :btn_success_bg, null: false, default: '$brand-success'
      t.string :btn_success_border, null: false, default: 'darken($btn-success-bg, 5%)'
      t.string :btn_info_color, null: false, default: '#fff'
      t.string :btn_info_bg, null: false, default: '$brand-info'
      t.string :btn_info_border, null: false, default: 'darken($btn-info-bg, 5%)'
      t.string :btn_warning_color, null: false, default: '#fff'
      t.string :btn_warning_bg, null: false, default: '$brand-warning'
      t.string :btn_warning_border, null: false, default: 'darken($btn-warning-bg, 5%)'
      t.string :btn_danger_color, null: false, default: '#fff'
      t.string :btn_danger_bg, null: false, default: '$brand-danger'
      t.string :btn_danger_border, null: false, default: 'darken($btn-danger-bg, 5%)'
      t.string :btn_link_disabled_color, null: false, default: '$gray-light'
      t.string :input_bg, null: false, default: '#fff'
      t.string :input_bg_disabled, null: false, default: '$gray-lighter'
      t.string :input_color, null: false, default: '$gray'
      t.string :input_border, null: false, default: '#ccc'
      t.string :input_border_radius, null: false, default: '$border-radius-base'
      t.string :input_border_radius_large, null: false, default: '$border-radius-large'
      t.string :input_border_radius_small, null: false, default: '$border-radius-small'
      t.string :input_border_focus, null: false, default: '#66afe9'
      t.string :input_color_placeholder, null: false, default: '#999'
      t.string :input_height_base, null: false, default: '($line-height-computed + ($padding-base-vertical * 2) + 2)'
      t.string :input_height_large, null: false, default: '(ceil($font-size-large * $line-height-large) + ($padding-large-vertical * 2) + 2)'
      t.string :input_height_small, null: false, default: '(floor($font-size-small * $line-height-small) + ($padding-small-vertical * 2) + 2)'
      t.string :legend_color, null: false, default: '$gray-dark'
      t.string :legend_border_color, null: false, default: '#e5e5e5'
      t.string :input_group_addon_bg, null: false, default: '$gray-lighter'
      t.string :input_group_addon_border_color, null: false, default: '$input-border'
      t.string :cursor_disabled, null: false, default: 'not-allowed'
      t.string :dropdown_bg, null: false, default: '#fff'
      t.string :dropdown_border, null: false, default: 'rgba(0,0,0,.15)'
      t.string :dropdown_fallback_border, null: false, default: '#ccc'
      t.string :dropdown_divider_bg, null: false, default: '#e5e5e5'
      t.string :dropdown_link_color, null: false, default: '$gray-dark'
      t.string :dropdown_link_hover_color, null: false, default: 'darken($gray-dark, 5%)'
      t.string :dropdown_link_hover_bg, null: false, default: '#f5f5f5'
      t.string :dropdown_link_active_color, null: false, default: '$component-active-color'
      t.string :dropdown_link_active_bg, null: false, default: '$component-active-bg'
      t.string :dropdown_link_disabled_color, null: false, default: '$gray-light'
      t.string :dropdown_header_color, null: false, default: '$gray-light'
      t.string :dropdown_caret_color, null: false, default: '#000'
      t.string :zindex_navbar, null: false, default: '1000'
      t.string :zindex_dropdown, null: false, default: '1000'
      t.string :zindex_popover, null: false, default: '1060'
      t.string :zindex_tooltip, null: false, default: '1070'
      t.string :zindex_navbar_fixed, null: false, default: '1030'
      t.string :zindex_modal, null: false, default: '1040'
      t.string :screen_xs, null: false, default: '480px'
      t.string :screen_xs_min, null: false, default: '$screen-xs'
      t.string :screen_phone, null: false, default: '$screen-xs-min'
      t.string :screen_sm, null: false, default: '768px'
      t.string :screen_sm_min, null: false, default: '$screen-sm'
      t.string :screen_tablet, null: false, default: '$screen-sm-min'
      t.string :screen_md, null: false, default: '992px'
      t.string :screen_md_min, null: false, default: '$screen-md'
      t.string :screen_desktop, null: false, default: '$screen-md-min'
      t.string :screen_lg, null: false, default: '1200px'
      t.string :screen_lg_min, null: false, default: '$screen-lg'
      t.string :screen_lg_desktop, null: false, default: '$screen-lg-min'
      t.string :screen_xs_max, null: false, default: '($screen-sm-min - 1)'
      t.string :screen_sm_max, null: false, default: '($screen-md-min - 1)'
      t.string :screen_md_max, null: false, default: '($screen-lg-min - 1)'
      t.string :grid_columns, null: false, default: '12'
      t.string :grid_gutter_width, null: false, default: '30px'
      t.string :grid_float_breakpoint, null: false, default: '$screen-sm-min'
      t.string :grid_float_breakpoint_max, null: false, default: '($grid-float-breakpoint - 1)'
      t.string :container_tablet, null: false, default: '(720px + $grid-gutter-width)'
      t.string :container_sm, null: false, default: '$container-tablet'
      t.string :container_desktop, null: false, default: '(940px + $grid-gutter-width)'
      t.string :container_md, null: false, default: '$container-desktop'
      t.string :container_large_desktop, null: false, default: '(1140px + $grid-gutter-width)'
      t.string :container_lg, null: false, default: '$container-large-desktop'
      t.string :navbar_height, null: false, default: '50px'
      t.string :navbar_margin_bottom, null: false, default: '$line-height-computed'
      t.string :navbar_border_radius, null: false, default: '$border-radius-base'
      t.string :navbar_padding_horizontal, null: false, default: 'floor(($grid-gutter-width / 2))'
      t.string :navbar_padding_vertical, null: false, default: '(($navbar-height - $line-height-computed) / 2)'
      t.string :navbar_collapse_max_height, null: false, default: '340px'
      t.string :navbar_default_color, null: false, default: '#777'
      t.string :navbar_default_bg, null: false, default: '#f8f8f8'
      t.string :navbar_default_border, null: false, default: 'darken($navbar-default-bg, 6.5%)'
      t.string :navbar_default_link_color, null: false, default: '#777'
      t.string :navbar_default_link_hover_color, null: false, default: '#333'
      t.string :navbar_default_link_hover_bg, null: false, default: 'transparent'
      t.string :navbar_default_link_active_color, null: false, default: '#555'
      t.string :navbar_default_link_active_bg, null: false, default: 'darken($navbar-default-bg, 6.5%)'
      t.string :navbar_default_link_disabled_color, null: false, default: '#ccc'
      t.string :navbar_default_link_disabled_bg, null: false, default: 'transparent'
      t.string :navbar_default_brand_color, null: false, default: '$navbar-default-link-color'
      t.string :navbar_default_brand_hover_color, null: false, default: 'darken($navbar-default-brand-color, 10%)'
      t.string :navbar_default_brand_hover_bg, null: false, default: 'transparent'
      t.string :navbar_default_toggle_hover_bg, null: false, default: '#ddd'
      t.string :navbar_default_toggle_icon_bar_bg, null: false, default: '#888'
      t.string :navbar_default_toggle_border_color, null: false, default: '#ddd'
      t.string :navbar_inverse_color, null: false, default: 'lighten($gray-light, 15%)'
      t.string :navbar_inverse_bg, null: false, default: '#222'
      t.string :navbar_inverse_border, null: false, default: 'darken($navbar-inverse-bg, 10%)'
      t.string :navbar_inverse_link_color, null: false, default: 'lighten($gray-light, 15%)'
      t.string :navbar_inverse_link_hover_color, null: false, default: '#fff'
      t.string :navbar_inverse_link_hover_bg, null: false, default: 'transparent'
      t.string :navbar_inverse_link_active_color, null: false, default: '$navbar-inverse-link-hover-color'
      t.string :navbar_inverse_link_active_bg, null: false, default: 'darken($navbar-inverse-bg, 10%)'
      t.string :navbar_inverse_link_disabled_color, null: false, default: '#444'
      t.string :navbar_inverse_link_disabled_bg, null: false, default: 'transparent'
      t.string :navbar_inverse_brand_color, null: false, default: '$navbar-inverse-link-color'
      t.string :navbar_inverse_brand_hover_color, null: false, default: '#fff'
      t.string :navbar_inverse_brand_hover_bg, null: false, default: 'transparent'
      t.string :navbar_inverse_toggle_hover_bg, null: false, default: '#333'
      t.string :navbar_inverse_toggle_icon_bar_bg, null: false, default: '#fff'
      t.string :navbar_inverse_toggle_border_color, null: false, default: '#333'
      t.string :nav_link_padding, null: false, default: '10px 15px'
      t.string :nav_link_hover_bg, null: false, default: '$gray-lighter'
      t.string :nav_disabled_link_color, null: false, default: '$gray-light'
      t.string :nav_disabled_link_hover_color, null: false, default: '$gray-light'
      t.string :nav_tabs_border_color, null: false, default: '#ddd'
      t.string :nav_tabs_link_hover_border_color, null: false, default: '$gray-lighter'
      t.string :nav_tabs_active_link_hover_bg, null: false, default: '$body-bg'
      t.string :nav_tabs_active_link_hover_color, null: false, default: '$gray'
      t.string :nav_tabs_active_link_hover_border_color, null: false, default: '#ddd'
      t.string :nav_tabs_justified_link_border_color, null: false, default: '#ddd'
      t.string :nav_tabs_justified_active_link_border_color, null: false, default: '$body-bg'
      t.string :nav_pills_border_radius, null: false, default: '$border-radius-base'
      t.string :nav_pills_active_link_hover_bg, null: false, default: '$component-active-bg'
      t.string :nav_pills_active_link_hover_color, null: false, default: '$component-active-color'
      t.string :pagination_color, null: false, default: '$link-color'
      t.string :pagination_bg, null: false, default: '#fff'
      t.string :pagination_border, null: false, default: '#ddd'
      t.string :pagination_hover_color, null: false, default: '$link-hover-color'
      t.string :pagination_hover_bg, null: false, default: '$gray-lighter'
      t.string :pagination_hover_border, null: false, default: '#ddd'
      t.string :pagination_active_color, null: false, default: '#fff'
      t.string :pagination_active_bg, null: false, default: '$brand-primary'
      t.string :pagination_active_border, null: false, default: '$brand-primary'
      t.string :pagination_disabled_color, null: false, default: '$gray-light'
      t.string :pagination_disabled_bg, null: false, default: '#fff'
      t.string :pagination_disabled_border, null: false, default: '#ddd'
      t.string :pager_bg, null: false, default: '$pagination-bg'
      t.string :pager_border, null: false, default: '$pagination-border'
      t.string :pager_border_radius, null: false, default: '15px'
      t.string :pager_hover_bg, null: false, default: '$pagination-hover-bg'
      t.string :pager_active_bg, null: false, default: '$pagination-active-bg'
      t.string :pager_active_color, null: false, default: '$pagination-active-color'
      t.string :pager_disabled_color, null: false, default: '$pagination-disabled-color'
      t.string :jumbotron_padding, null: false, default: '30px'
      t.string :jumbotron_color, null: false, default: 'inherit'
      t.string :jumbotron_bg, null: false, default: '$gray-lighter'
      t.string :jumbotron_heading_color, null: false, default: 'inherit'
      t.string :jumbotron_font_size, null: false, default: 'ceil(($font-size-base * 1.5))'
      t.string :state_success_text, null: false, default: '#3c763d'
      t.string :state_success_bg, null: false, default: '#dff0d8'
      t.string :state_success_border, null: false, default: 'darken(adjust-hue($state-success-bg, -10), 5%)'
      t.string :state_info_text, null: false, default: '#31708f'
      t.string :state_info_bg, null: false, default: '#d9edf7'
      t.string :state_info_border, null: false, default: 'darken(adjust-hue($state-info-bg, -10), 7%)'
      t.string :state_warning_text, null: false, default: '#8a6d3b'
      t.string :state_warning_bg, null: false, default: '#fcf8e3'
      t.string :state_warning_border, null: false, default: 'darken(adjust-hue($state-warning-bg, -10), 5%)'
      t.string :state_danger_text, null: false, default: '#a94442'
      t.string :state_danger_bg, null: false, default: '#f2dede'
      t.string :state_danger_border, null: false, default: 'darken(adjust-hue($state-danger-bg, -10), 5%)'
      t.string :tooltip_max_width, null: false, default: '200px'
      t.string :tooltip_color, null: false, default: '#fff'
      t.string :tooltip_bg, null: false, default: '#000'
      t.string :tooltip_opacity, null: false, default: '.9'
      t.string :tooltip_arrow_width, null: false, default: '5px'
      t.string :tooltip_arrow_color, null: false, default: '$tooltip-bg'
      t.string :popover_bg, null: false, default: '#fff'
      t.string :popover_max_width, null: false, default: '276px'
      t.string :popover_border_color, null: false, default: 'rgba(0,0,0,.2)'
      t.string :popover_fallback_border_color, null: false, default: '#ccc'
      t.string :popover_title_bg, null: false, default: 'darken($popover-bg, 3%)'
      t.string :popover_arrow_width, null: false, default: '10px'
      t.string :popover_arrow_color, null: false, default: '$popover-bg'
      t.string :popover_arrow_outer_width, null: false, default: '($popover-arrow-width + 1)'
      t.string :popover_arrow_outer_color, null: false, default: 'fade_in($popover-border-color, 0.05)'
      t.string :popover_arrow_outer_fallback_color, null: false, default: 'darken($popover-fallback-border-color, 20%)'
      t.string :label_default_bg, null: false, default: '$gray-light'
      t.string :label_primary_bg, null: false, default: '$brand-primary'
      t.string :label_success_bg, null: false, default: '$brand-success'
      t.string :label_info_bg, null: false, default: '$brand-info'
      t.string :label_warning_bg, null: false, default: '$brand-warning'
      t.string :label_danger_bg, null: false, default: '$brand-danger'
      t.string :label_color, null: false, default: '#fff'
      t.string :label_link_hover_color, null: false, default: '#fff'
      t.string :modal_inner_padding, null: false, default: '15px'
      t.string :modal_title_padding, null: false, default: '15px'
      t.string :modal_title_line_height, null: false, default: '$line-height-base'
      t.string :modal_content_bg, null: false, default: '#fff'
      t.string :modal_content_border_color, null: false, default: 'rgba(0,0,0,.2)'
      t.string :modal_content_fallback_border_color, null: false, default: '#999'
      t.string :modal_backdrop_bg, null: false, default: '#000'
      t.string :modal_backdrop_opacity, null: false, default: '.5'
      t.string :modal_header_border_color, null: false, default: '#e5e5e5'
      t.string :modal_footer_border_color, null: false, default: '$modal-header-border-color'
      t.string :modal_lg, null: false, default: '900px'
      t.string :modal_md, null: false, default: '600px'
      t.string :modal_sm, null: false, default: '300px'
      t.string :alert_padding, null: false, default: '15px'
      t.string :alert_border_radius, null: false, default: '$border-radius-base'
      t.string :alert_link_font_weight, null: false, default: 'bold'
      t.string :alert_success_bg, null: false, default: '$state-success-bg'
      t.string :alert_success_text, null: false, default: '$state-success-text'
      t.string :alert_success_border, null: false, default: '$state-success-border'
      t.string :alert_info_bg, null: false, default: '$state-info-bg'
      t.string :alert_info_text, null: false, default: '$state-info-text'
      t.string :alert_info_border, null: false, default: '$state-info-border'
      t.string :alert_warning_bg, null: false, default: '$state-warning-bg'
      t.string :alert_warning_text, null: false, default: '$state-warning-text'
      t.string :alert_warning_border, null: false, default: '$state-warning-border'
      t.string :alert_danger_bg, null: false, default: '$state-danger-bg'
      t.string :alert_danger_text, null: false, default: '$state-danger-text'
      t.string :alert_danger_border, null: false, default: '$state-danger-border'
      t.string :progress_bg, null: false, default: '#f5f5f5'
      t.string :progress_bar_color, null: false, default: '#fff'
      t.string :progress_border_radius, null: false, default: '$border-radius-base'
      t.string :progress_bar_bg, null: false, default: '$brand-primary'
      t.string :progress_bar_success_bg, null: false, default: '$brand-success'
      t.string :progress_bar_warning_bg, null: false, default: '$brand-warning'
      t.string :progress_bar_danger_bg, null: false, default: '$brand-danger'
      t.string :progress_bar_info_bg, null: false, default: '$brand-info'
      t.string :list_group_bg, null: false, default: '#fff'
      t.string :list_group_border, null: false, default: '#ddd'
      t.string :list_group_border_radius, null: false, default: '$border-radius-base'
      t.string :list_group_hover_bg, null: false, default: '#f5f5f5'
      t.string :list_group_active_color, null: false, default: '$component-active-color'
      t.string :list_group_active_bg, null: false, default: '$component-active-bg'
      t.string :list_group_active_border, null: false, default: '$list-group-active-bg'
      t.string :list_group_active_text_color, null: false, default: 'lighten($list-group-active-bg, 40%)'
      t.string :list_group_disabled_color, null: false, default: '$gray-light'
      t.string :list_group_disabled_bg, null: false, default: '$gray-lighter'
      t.string :list_group_disabled_text_color, null: false, default: '$list-group-disabled-color'
      t.string :list_group_link_color, null: false, default: '#555'
      t.string :list_group_link_hover_color, null: false, default: '$list-group-link-color'
      t.string :list_group_link_heading_color, null: false, default: '#333'
      t.string :panel_bg, null: false, default: '#fff'
      t.string :panel_body_padding, null: false, default: '15px'
      t.string :panel_heading_padding, null: false, default: '10px 15px'
      t.string :panel_footer_padding, null: false, default: '$panel-heading-padding'
      t.string :panel_border_radius, null: false, default: '$border-radius-base'
      t.string :panel_inner_border, null: false, default: '#ddd'
      t.string :panel_footer_bg, null: false, default: '#f5f5f5'
      t.string :panel_default_text, null: false, default: '$gray-dark'
      t.string :panel_default_border, null: false, default: '#ddd'
      t.string :panel_default_heading_bg, null: false, default: '#f5f5f5'
      t.string :panel_primary_text, null: false, default: '#fff'
      t.string :panel_primary_border, null: false, default: '$brand-primary'
      t.string :panel_primary_heading_bg, null: false, default: '$brand-primary'
      t.string :panel_success_text, null: false, default: '$state-success-text'
      t.string :panel_success_border, null: false, default: '$state-success-border'
      t.string :panel_success_heading_bg, null: false, default: '$state-success-bg'
      t.string :panel_info_text, null: false, default: '$state-info-text'
      t.string :panel_info_border, null: false, default: '$state-info-border'
      t.string :panel_info_heading_bg, null: false, default: '$state-info-bg'
      t.string :panel_warning_text, null: false, default: '$state-warning-text'
      t.string :panel_warning_border, null: false, default: '$state-warning-border'
      t.string :panel_warning_heading_bg, null: false, default: '$state-warning-bg'
      t.string :panel_danger_text, null: false, default: '$state-danger-text'
      t.string :panel_danger_border, null: false, default: '$state-danger-border'
      t.string :panel_danger_heading_bg, null: false, default: '$state-danger-bg'
      t.string :thumbnail_padding, null: false, default: '4px'
      t.string :thumbnail_bg, null: false, default: '$body-bg'
      t.string :thumbnail_border, null: false, default: '#ddd'
      t.string :thumbnail_border_radius, null: false, default: '$border-radius-base'
      t.string :thumbnail_caption_color, null: false, default: '$text-color'
      t.string :thumbnail_caption_padding, null: false, default: '9px'
      t.string :well_bg, null: false, default: '#f5f5f5'
      t.string :well_border, null: false, default: 'darken($well-bg, 7%)'
      t.string :badge_color, null: false, default: '#fff'
      t.string :badge_link_hover_color, null: false, default: '#fff'
      t.string :badge_bg, null: false, default: '$gray-light'
      t.string :badge_active_color, null: false, default: '$link-color'
      t.string :badge_active_bg, null: false, default: '#fff'
      t.string :badge_font_weight, null: false, default: 'bold'
      t.string :badge_line_height, null: false, default: '1'
      t.string :badge_border_radius, null: false, default: '10px'
      t.string :breadcrumb_padding_vertical, null: false, default: '8px'
      t.string :breadcrumb_padding_horizontal, null: false, default: '15px'
      t.string :breadcrumb_bg, null: false, default: '#f5f5f5'
      t.string :breadcrumb_color, null: false, default: '#ccc'
      t.string :breadcrumb_active_color, null: false, default: '$gray-light'
      t.string :breadcrumb_separator, null: false, default: '"/"'
      t.string :carousel_text_shadow, null: false, default: '0 1px 2px rgba(0,0,0,.6)'
      t.string :carousel_control_color, null: false, default: '#fff'
      t.string :carousel_control_width, null: false, default: '15%'
      t.string :carousel_control_opacity, null: false, default: '.5'
      t.string :carousel_control_font_size, null: false, default: '20px'
      t.string :carousel_indicator_active_bg, null: false, default: '#fff'
      t.string :carousel_indicator_border_color, null: false, default: '#fff'
      t.string :carousel_caption_color, null: false, default: '#fff'
      t.string :close_font_weight, null: false, default: 'bold'
      t.string :close_color, null: false, default: '#000'
      t.string :close_text_shadow, null: false, default: '0 1px 0 #fff'
      t.string :code_color, null: false, default: '#c7254e'
      t.string :code_bg, null: false, default: '#f9f2f4'
      t.string :kbd_color, null: false, default: '#fff'
      t.string :kbd_bg, null: false, default: '#333'
      t.string :pre_bg, null: false, default: '#f5f5f5'
      t.string :pre_color, null: false, default: '$gray-dark'
      t.string :pre_border_color, null: false, default: '#ccc'
      t.string :pre_scrollable_max_height, null: false, default: '340px'
      t.string :component_offset_horizontal, null: false, default: '180px'
      t.string :text_muted, null: false, default: '$gray-light'
      t.string :abbr_border_color, null: false, default: '$gray-light'
      t.string :headings_small_color, null: false, default: '$gray-light'
      t.string :blockquote_small_color, null: false, default: '$gray-light'
      t.string :blockquote_font_size, null: false, default: '($font-size-base * 1.25)'
      t.string :blockquote_border_color, null: false, default: '$gray-lighter'
      t.string :page_header_border_color, null: false, default: '$gray-lighter'
      t.string :dl_horizontal_offset, null: false, default: '$component-offset-horizontal'
      t.string :hr_border, null: false, default: '$gray-lighter'

      t.timestamps
    end
  end
end
