class Stylesheet < ActiveRecord::Base

  before_save :update_stylesheet_and_fingerprint

  def update_stylesheet_and_fingerprint

    self.user_stylesheet = Sass::Engine.new(ERB.new(File.read(Rails.root.join('app', 'assets', 'stylesheets', 'user_stylesheet.css.scss.erb'))).result(binding), :syntax => :scss, :cache => false).render

    self.fingerprint = Digest::SHA256.hexdigest self.user_stylesheet
  end

  def self.variable_names
    %w{
      gray_base
      gray_darker
      gray_dark
      gray
      gray_light
      gray_lighter
      brand_primary
      brand_success
      brand_info
      brand_warning
      brand_danger
      body_bg
      text_color
      link_color
      link_hover_color
      link_hover_decoration
      font_family_sans_serif
      font_family_serif
      font_family_monospace
      font_family_base
      font_size_base
      font_size_large
      font_size_small
      font_size_h1
      font_size_h2
      font_size_h3
      font_size_h4
      font_size_h5
      font_size_h6
      line_height_base
      line_height_computed
      headings_font_family
      headings_font_weight
      headings_line_height
      headings_color
      icon_font_path
      icon_font_name
      icon_font_svg_id
      padding_base_vertical
      padding_base_horizontal
      padding_large_vertical
      padding_large_horizontal
      padding_small_vertical
      padding_small_horizontal
      padding_xs_vertical
      padding_xs_horizontal
      line_height_large
      line_height_small
      border_radius_base
      border_radius_large
      border_radius_small
      component_active_color
      component_active_bg
      caret_width_base
      caret_width_large
      table_cell_padding
      table_condensed_cell_padding
      table_bg
      table_bg_accent
      table_bg_hover
      table_bg_active
      table_border_color
      btn_font_weight
      btn_default_color
      btn_default_bg
      btn_default_border
      btn_primary_color
      btn_primary_bg
      btn_primary_border
      btn_success_color
      btn_success_bg
      btn_success_border
      btn_info_color
      btn_info_bg
      btn_info_border
      btn_warning_color
      btn_warning_bg
      btn_warning_border
      btn_danger_color
      btn_danger_bg
      btn_danger_border
      btn_link_disabled_color
      input_bg
      input_bg_disabled
      input_color
      input_border
      input_border_radius
      input_border_radius_large
      input_border_radius_small
      input_border_focus
      input_color_placeholder
      input_height_base
      input_height_large
      input_height_small
      legend_color
      legend_border_color
      input_group_addon_bg
      input_group_addon_border_color
      cursor_disabled
      dropdown_bg
      dropdown_border
      dropdown_fallback_border
      dropdown_divider_bg
      dropdown_link_color
      dropdown_link_hover_color
      dropdown_link_hover_bg
      dropdown_link_active_color
      dropdown_link_active_bg
      dropdown_link_disabled_color
      dropdown_header_color
      dropdown_caret_color
      zindex_navbar
      zindex_dropdown
      zindex_popover
      zindex_tooltip
      zindex_navbar_fixed
      zindex_modal
      screen_xs
      screen_xs_min
      screen_phone
      screen_sm
      screen_sm_min
      screen_tablet
      screen_md
      screen_md_min
      screen_desktop
      screen_lg
      screen_lg_min
      screen_lg_desktop
      screen_xs_max
      screen_sm_max
      screen_md_max
      grid_columns
      grid_gutter_width
      grid_float_breakpoint
      grid_float_breakpoint_max
      container_tablet
      container_sm
      container_desktop
      container_md
      container_large_desktop
      container_lg
      navbar_height
      navbar_margin_bottom
      navbar_border_radius
      navbar_padding_horizontal
      navbar_padding_vertical
      navbar_collapse_max_height
      navbar_default_color
      navbar_default_bg
      navbar_default_border
      navbar_default_link_color
      navbar_default_link_hover_color
      navbar_default_link_hover_bg
      navbar_default_link_active_color
      navbar_default_link_active_bg
      navbar_default_link_disabled_color
      navbar_default_link_disabled_bg
      navbar_default_brand_color
      navbar_default_brand_hover_color
      navbar_default_brand_hover_bg
      navbar_default_toggle_hover_bg
      navbar_default_toggle_icon_bar_bg
      navbar_default_toggle_border_color
      navbar_inverse_color
      navbar_inverse_bg
      navbar_inverse_border
      navbar_inverse_link_color
      navbar_inverse_link_hover_color
      navbar_inverse_link_hover_bg
      navbar_inverse_link_active_color
      navbar_inverse_link_active_bg
      navbar_inverse_link_disabled_color
      navbar_inverse_link_disabled_bg
      navbar_inverse_brand_color
      navbar_inverse_brand_hover_color
      navbar_inverse_brand_hover_bg
      navbar_inverse_toggle_hover_bg
      navbar_inverse_toggle_icon_bar_bg
      navbar_inverse_toggle_border_color
      nav_link_padding
      nav_link_hover_bg
      nav_disabled_link_color
      nav_disabled_link_hover_color
      nav_tabs_border_color
      nav_tabs_link_hover_border_color
      nav_tabs_active_link_hover_bg
      nav_tabs_active_link_hover_color
      nav_tabs_active_link_hover_border_color
      nav_tabs_justified_link_border_color
      nav_tabs_justified_active_link_border_color
      nav_pills_border_radius
      nav_pills_active_link_hover_bg
      nav_pills_active_link_hover_color
      pagination_color
      pagination_bg
      pagination_border
      pagination_hover_color
      pagination_hover_bg
      pagination_hover_border
      pagination_active_color
      pagination_active_bg
      pagination_active_border
      pagination_disabled_color
      pagination_disabled_bg
      pagination_disabled_border
      pager_bg
      pager_border
      pager_border_radius
      pager_hover_bg
      pager_active_bg
      pager_active_color
      pager_disabled_color
      jumbotron_padding
      jumbotron_color
      jumbotron_bg
      jumbotron_heading_color
      jumbotron_font_size
      state_success_text
      state_success_bg
      state_success_border
      state_info_text
      state_info_bg
      state_info_border
      state_warning_text
      state_warning_bg
      state_warning_border
      state_danger_text
      state_danger_bg
      state_danger_border
      tooltip_max_width
      tooltip_color
      tooltip_bg
      tooltip_opacity
      tooltip_arrow_width
      tooltip_arrow_color
      popover_bg
      popover_max_width
      popover_border_color
      popover_fallback_border_color
      popover_title_bg
      popover_arrow_width
      popover_arrow_color
      popover_arrow_outer_width
      popover_arrow_outer_color
      popover_arrow_outer_fallback_color
      label_default_bg
      label_primary_bg
      label_success_bg
      label_info_bg
      label_warning_bg
      label_danger_bg
      label_color
      label_link_hover_color
      modal_inner_padding
      modal_title_padding
      modal_title_line_height
      modal_content_bg
      modal_content_border_color
      modal_content_fallback_border_color
      modal_backdrop_bg
      modal_backdrop_opacity
      modal_header_border_color
      modal_footer_border_color
      modal_lg
      modal_md
      modal_sm
      alert_padding
      alert_border_radius
      alert_link_font_weight
      alert_success_bg
      alert_success_text
      alert_success_border
      alert_info_bg
      alert_info_text
      alert_info_border
      alert_warning_bg
      alert_warning_text
      alert_warning_border
      alert_danger_bg
      alert_danger_text
      alert_danger_border
      progress_bg
      progress_bar_color
      progress_border_radius
      progress_bar_bg
      progress_bar_success_bg
      progress_bar_warning_bg
      progress_bar_danger_bg
      progress_bar_info_bg
      list_group_bg
      list_group_border
      list_group_border_radius
      list_group_hover_bg
      list_group_active_color
      list_group_active_bg
      list_group_active_border
      list_group_active_text_color
      list_group_disabled_color
      list_group_disabled_bg
      list_group_disabled_text_color
      list_group_link_color
      list_group_link_hover_color
      list_group_link_heading_color
      panel_bg
      panel_body_padding
      panel_heading_padding
      panel_footer_padding
      panel_border_radius
      panel_inner_border
      panel_footer_bg
      panel_default_text
      panel_default_border
      panel_default_heading_bg
      panel_primary_text
      panel_primary_border
      panel_primary_heading_bg
      panel_success_text
      panel_success_border
      panel_success_heading_bg
      panel_info_text
      panel_info_border
      panel_info_heading_bg
      panel_warning_text
      panel_warning_border
      panel_warning_heading_bg
      panel_danger_text
      panel_danger_border
      panel_danger_heading_bg
      thumbnail_padding
      thumbnail_bg
      thumbnail_border
      thumbnail_border_radius
      thumbnail_caption_color
      thumbnail_caption_padding
      well_bg
      well_border
      badge_color
      badge_link_hover_color
      badge_bg
      badge_active_color
      badge_active_bg
      badge_font_weight
      badge_line_height
      badge_border_radius
      breadcrumb_padding_vertical
      breadcrumb_padding_horizontal
      breadcrumb_bg
      breadcrumb_color
      breadcrumb_active_color
      breadcrumb_separator
      carousel_text_shadow
      carousel_control_color
      carousel_control_width
      carousel_control_opacity
      carousel_control_font_size
      carousel_indicator_active_bg
      carousel_indicator_border_color
      carousel_caption_color
      close_font_weight
      close_color
      close_text_shadow
      code_color
      code_bg
      kbd_color
      kbd_bg
      pre_bg
      pre_color
      pre_border_color
      pre_scrollable_max_height
      component_offset_horizontal
      text_muted
      abbr_border_color
      headings_small_color
      blockquote_small_color
      blockquote_font_size
      blockquote_border_color
      page_header_border_color
      dl_horizontal_offset
      hr_border
      user_stylesheet
      fingerprint
    }
  end
end
